project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracker.urls')),
]

tracker/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views

app_name = 'tracker'

urlpatterns = [
     path('', views.index, name = 'index'),
     path('map', views.map, name = 'map'),
     path('sightings', views.sightings, name = 'sightings'),
     path('sightings/stats', views.stat, name = 'stats'),
     path('sightings/<str:Unique_Squirrel_ID>/', views.detail, name='detail'),
     path('sightings/add', views.add, name = 'add'),
]

tracker/models.py
from django.db import models
from datetime import datetime
from django.utils import timezone

class Squirrel(models.Model):

    X = models.FloatField()
    Y = models.FloatField()
    Unique_Squirrel_ID = models.CharField(max_length = 50)
    Shift_Choices = [('AM','AM'),('PM','PM'),]
    Hectare = models.CharField(max_length = 10, null = True, blank = True)
    Shift = models.CharField(max_length = 10, choices = Shift_Choices)
    Date = models.DateTimeField(default=timezone.now)
    Hectare_Squirrel_Number = models.IntegerField(null = True, blank = True)
    Age_Choices = [('Adult','Adult'),('Juvenile','Juvenile'),]
    Age = models.CharField(max_length = 20, choices = Age_Choices, null = True, blank = True)
    Fur_Choices = [('Gray','Gray'),('Cinnamon','Cinnamon'),('Black','Black'),]
    Primary_Fur_Color = models.CharField(max_length=20, choices = Fur_Choices, null = True, blank = True)
    Highlight_Fur_Color = models.CharField(max_length=30, null = True, blank = True)
    Combination_of_Primary_and_Highlight_Color = models.CharField(max_length=40,null = True, blank = True)
    Color_notes = models.CharField(max_length = 60, null = True, blank = True)
    Location_Choices = [('Above Ground','Above Ground'),('Ground Plane','Ground Plane'),]
    Location = models.CharField(max_length = 30, choices = Location_Choices, null = True, blank = True)
    Above_Ground_Sighter_Measurement = models.CharField(max_length = 10, null = True, blank = True)
    Specific_Location = models.CharField(max_length = 40, null = True, blank = True)
    Running = models.BooleanField(null = True, blank = True)
    Chasing = models.BooleanField(null = True, blank = True)
    Climbing = models.BooleanField(null = True, blank = True)
    Eating = models.BooleanField(null = True, blank = True)
    Foraging = models.BooleanField(null = True, blank = True)
    Other_Activities = models.CharField(max_length = 30, null = True, blank = True)
    Kuks = models.BooleanField(null = True, blank = True)
    Quaas = models.BooleanField(null = True, blank = True)
    Moans = models.BooleanField(null = True, blank = True)
    Tail_flags = models.BooleanField(null = True, blank = True)
    Tail_twitches = models.BooleanField(null = True, blank = True)
    Approaches = models.BooleanField(null = True, blank = True)
    Indifferent = models.BooleanField(null = True, blank = True)
    Runs_from = models.BooleanField(null = True, blank = True)
    Other_Interactions = models.CharField(max_length = 40, null = True, blank = True)
    Lat_Long = models.CharField(max_length = 80, null = True, blank = True)


    def __str__(self):
        return f"ID: {self.Unique_Squirrel_ID} Date: {self.Date}"

tracker/forms.py
from django.forms import ModelForm
from .models import Squirrel

class AddSightingsForm(ModelForm):
    class Meta:
        model = Squirrel
        fields = [
                'X',
                'Y',
                'Unique_Squirrel_ID',
                'Shift',
                'Date'
        ]

class UpdateForm(ModelForm):
    class Meta:
        model = Squirrel
        fields = [
                'X',
                'Y',
                'Unique_Squirrel_ID',
                'Shift',
                'Date',
                'Age'
                ]

tracker/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Squirrel
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from .forms import AddSightingsForm
from .forms import UpdateForm
from django.db.models import Avg, Count, When, Case, Q

def index(request):
    return render(request, 'tracker/home.html',{})

def map(request):
    squirrels = Squirrel.objects.all()[:100]
    context = {
            'sightings': squirrels,
            }

    return render(request, 'tracker/map.html',context)

def sightings(request):
    squirrels = Squirrel.objects.all()
    context = {
            'squirrels': squirrels,
            }

    return render(request, 'tracker/sightings.html',context)

def stat(request):
    stats  =[{'Average Latitude of Sightings': Squirrel.objects.aggregate(Avg('X'))},
            {'Average Longitude of Sightings': Squirrel.objects.aggregate(Avg('Y'))},
            {'Number of Sightings where Squirrels are Adult': Squirrel.objects.filter(Age = 'Adult').count()},
            {'Number of Sightings where Primary Fur Color of Squirrels are Gray': Squirrel.objects.filter(Primary_Fur_Color = 'Gray').count()},
            {'Number of Sightings where Squirrels are Chasing': Squirrel.objects.filter(Chasing = True).count()},
            ]
    context = {
            'stats': stats,
            }

    return render(request, 'tracker/stat.html', context)

def detail(request, Unique_Squirrel_ID):
    squirrel = Squirrel.objects.get(Unique_Squirrel_ID=Unique_Squirrel_ID)
    form = UpdateForm(instance = squirrel)
    if request.method == 'POST':
        form = UpdateForm(request.POST, instance=squirrel)
        if form.is_valid():
            form.save()
            return redirect('/sightings')

    context = {
            'squirrel':  squirrel,
            'form': form,
            }

    return render(request, 'tracker/detail.html',context)

def add(request):
    if request.method == 'POST':
        form = AddSightingsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/sightings')
        else:
            return JsonResponse({'errors': form.errors}, status = 400)
    return render(request, 'tracker/add.html', {})

def showthis(request):
    Squirrel.objects.all().delete()
    context()
    return render(request, 'tracker/home_page.html', context)     

tracker/templates/tracker/add.html
{% extends 'tracker/base.html' %}

{% load static %}

{% block title %}
- Add Sightings
{% endblock %}

{% block main %}
<html>
 <body>
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div>
            <div class="card mb-3 shadow-sm">
              <img class="bd-placeholder-img card-img-top"
                   width="225" height="225" preserveAspectRatio="xMidYMid slice"
                   focusable="false" role="img" aria-label="{{ pet.name }}"
                   src="https://i.guim.co.uk/img/media/3aa0344c8039b86f4f7bd3981ae81d54dc985119/0_137_2741_1644/master/2741.jpg?width=1920&quality=85&auto=format&fit=max&s=f332c5d4c44722442e1d1ef42893322d"></img>
            </div>
          </div>
	  <form id = 'submit' action = '' method = 'POST' class = 'input-group mb-3'>
		    {% csrf_token %}

		    <p>
		    	<input type = 'text'
		     	name = 'X'
		     	class = 'form-control'
		    	placeholder='Latitude'
		    	aria-label ='Latitude'>
		    </p>

		    <p>
			<input type = 'text'
			name = 'Y'
			class = 'form-control'
			placeholder='Longitude'
			aria-label ='Longitude'>
		    </p>

		    <p>
			<input type = 'text'
                    	name = 'Unique_Squirrel_ID'
                    	class = 'form-control'
                    	placeholder='Unique Squirrel ID'
                    	aria-label ='Unique Squirrel ID'>
		    </p>

		    <p>
		    	<input type = 'text'
			name = 'Shift'
			class = 'form-control'
		    	placeholder='Shift'
			aria-label = 'Shift'>
		    </p>

		    <p>
			<input type = 'date'
			name = 'Date'
		   	class = 'form-control'
			placeholder='Date'
			aria_label = 'Date'>
		    </p>
		  
		    <p>
			<input type = 'text'
			name = 'Age'
		   	class = 'form-control'
			placeholder='Age'
			aria_label = 'Age'>
		    </p>
		  
		    <p>
			<input type = 'text'
			name = 'Primary Fur Color'
		   	class = 'form-control'
			placeholder='Primary Fur Color'
			aria_label = 'Primary Fur Color'>
		    </p>
		  
		    <p>
			<input type = 'text'
			name = 'Location'
		   	class = 'form-control'
			placeholder='Location'
			aria_label = 'Location'>
		    </p>
		  
		    <p>
			<input type = 'text'
			name = 'Specific Location'
		   	class = 'form-control'
			placeholder='Specific Location'
			aria_label = 'Specific Location'>
		    </p>
		  
		    <p>
			<input type = 'text'
			name = 'Other Activities'
		   	class = 'form-control'
			placeholder='Other Activities'
			aria_label = 'Other Activities'>
		    </p>
		  
		  
		   <p>
			<label class="form-check-label" for="same-address">Running</label>
			<input type = 'checkbox'
			name = 'Running'
		   	class = 'form-check'
			placeholder='Running'
			aria_label = 'Running'>
		    </p>
		  
		   <p>
			<label class="form-check-label" for="same-address">Chasing</label>
			<input type = 'checkbox'
			name = 'Chasing'
		   	class = 'form-check'
			placeholder='Chasing'
			aria_label = 'Chasing'>
		    </p>
		  
		   <p>
			<label class="form-check-label" for="same-address">Climbing</label>
			<input type = 'checkbox'
			name = 'Climbing'
		   	class = 'form-check'
			placeholder='Climbing'
			aria_label = 'Climbing'>
		    </p>
		  
		   <p>
			<label class="form-check-label" for="same-address">Eating</label>
			<input type = 'checkbox'
			name = 'Eating'
		   	class = 'form-check'
			placeholder='Eating'
			aria_label = 'Eating'>
		    </p>
		  
		   <p>
			<label class="form-check-label" for="same-address">Foraging</label>
			<input type = 'checkbox'
			name = 'Foraging'
		   	class = 'form-check'
			placeholder='Foraging'
			aria_label = 'Foraging'>
		    </p>
		  
		   <p>
			<label class="form-check-label" for="same-address">Kuks</label>
			<input type = 'checkbox'
			name = 'Kuks'
		   	class = 'form-check'
			placeholder='Kuks'
			aria_label = 'Kuks'>
		    </p>
		  
		   <p>
			<label class="form-check-label" for="same-address">Quass</label>
			<input type = 'checkbox'
			name = 'Quass'
		   	class = 'form-check'
			placeholder='Quass'
			aria_label = 'Quass'>
		    </p>
		  
		   <p>
			<label class="form-check-label" for="same-address">Moans</label>
			<input type = 'checkbox'
			name = 'Moans'
		   	class = 'form-check'
			placeholder='Moans'
			aria_label = 'Moans'>
		    </p>
		  
		  <p>
			<label class="form-check-label" for="same-address">Tail flags</label>
			<input type = 'checkbox'
			name = 'Tail flags'
		   	class = 'form-check'
			placeholder='Tail flags'
			aria_label = 'Tail flags'>
		    </p>
		  
		  <p>
			<label class="form-check-label" for="same-address">Tail twitches</label>
			<input type = 'checkbox'
			name = 'Tail twitches'
		   	class = 'form-check'
			placeholder='Tail twitches'
			aria_label = 'Tail twitches'>
		    </p>
		  
		  <p>
			<label class="form-check-label" for="same-address">Approaches</label>
			<input type = 'checkbox'
			name = 'Approaches'
		   	class = 'form-check'
			placeholder='Approaches'
			aria_label = 'Approaches'>
		    </p>
		  
		  <p>
			<label class="form-check-label" for="same-address">Indifferent</label>
			<input type = 'checkbox'
			name = 'Indifferent'
		   	class = 'form-check'
			placeholder='Indifferent'
			aria_label = 'Indifferent'>
		    </p>
		  
		  <p>
			<label class="form-check-label" for="same-address">Runs from</label>
			<input type = 'checkbox'
			name = 'Runs from'
		   	class = 'form-check'
			placeholder='Runs from'
			aria_label = 'Runs from'>
		    </p>
		  
		  
		  
		    
		    <div class = 'input-group-append'>
			    <p> <button class='btn btn-outline-secondary'  type = 'submit'>Add</button></p>
		    </div>
		    <div id = 'errors' class = 'mb-3'></div>
	    </form>
         </div>
       </div>
    </div>
  </div>
 </body>
</html>

{% endblock %}

tracker/templates/tracker/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Squirrel Tracker Syetem{% block title %}{% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/album/">

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.3/examples/album/album.css" rel="stylesheet">
  </head>
  <body>

    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">Introduction</h4>
              <p class="text-muted">This is a visulization application of squirrel tracker at Central Park.</p>
	    </div>
	    <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Guidence</h4>
              <ul class="list-unstyled">
                <li><a href="{% url 'tracker:map' %}" class="text-white">Map</a></li>
                <li><a href="{% url 'tracker:add' %}" class="text-white">Add</a></li>
                <li><a href="{% url 'tracker:sightings' %}" class="text-white">Sightings</a></li>
                <li><a href="{% url 'tracker:stats' %}" class="text-white">Stat</a></li>
              </ul>
	    </div>
	  </div>
	 </div>
       </div>
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
          <a href="{% url 'tracker:index' %}" class="navbar-brand d-flex align-items-center">
            <strong>Squirrels at Central Park</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">
      {% block main %}
      {% endblock %}
    </main>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>&copy; 2020 Add More Sightings, Inc.</p>
      </div>
    </footer>

    {# Don't use the slim version of jQuery! It does not have the ajax librarires! #}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="https://getbootstrap.com/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
    {% block extra_footer %}
    {% endblock %}
  </body>

 </html>

tracker/templates/tracker/detail.html
{% extends 'tracker/base.html' %}

{% load static %}

{% block title %} -Update Squirrel Information {% endblock %} 

{% block main  %}

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        <div class="col-md-4">



	      <div class="col-md-30">
                <div class="card mb-8 shadow-sm">
                  <div class="card-body">
              	    <p class="card-text">
                      <b>Original Information:</b>
                	<div>
                  	  <span class="text-muted font-italic">ID:</span>
                  	  <span>
                            {{ squirrel.Unique_Squirrel_ID }}
                  	  </span>
                	</div>
                        <div>
                  	  <span class="text-muted font-italic">Date of Sightings:</span>
                  	  <span>
                    	    {{ squirrel.Date }}
                  	  </span>
                        </div>
                        <div>
                  	  <span class="text-muted font-italic">Coordinates(X, Y):</span>
                  	  <span>
			    {{ squirrel.X}},{{squirrel.Y}}
                  	  </span>
                        </div>
              	    </p>
            	  </div>
                </div>
       	      </div>

	   <p></p>

	      <div class="col-md-8">
	      	<b>Update Information:</b>
	      </div>
	   <p></p>
            <div class="col-md-4">   
		<form action='' method='POST'>
			{% csrf_token %}
			{{form}}
			<p></p>
			<p> <button class='btn btn-outline-secondary'  type = 'submit'>Update</button></p>

    		</form>
	    </div>		
        </div>
      </div>
    </div>       
  </div>		
{% endblock %}

tracker/templates/tracker/home.html
{% extends 'tracker/base.html' %}
{% load static %}
{% block title %} -Squirrel Tracker Homepage {% endblock %} 
{% block main  %}

<html>
	<body>
	  <div class="album py-5 bg-light">
	    <div class = 'container'>
	      <div class = 'row'>
		 <div class="col-md-6">
			<b style="font-size:25px">Welcome to Squirrel Tracker System.</b>
		 </div>
		 <p></p>
            	 <div class="card mb-5 shadow-sm">
              	   <img
                   width="800" height="450" preserveAspectRatio="xMidYMid slice"
                   focusable="false" role="img"
                   src="https://www.eekwi.org/sites/default/files/2019-11/greysquirrel.jpg"></img>
            	 </div>
	     </div>
	   </div>
	  </div> 
	</body>
</html>
{% endblock %}

tracker/templates/tracker/map.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet"
          href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
            integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
            crossorigin=""></script>

    <style>
      html,body {
        height: 100%;
      }
    </style>
  </head>
  <body>
    <div id="map" class="container-fluid h-100"></div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Leaflet JS -->
    <script>
        var map_center = [
            40.782091,  // Latitude
            -73.964285  // Longitude
        ];
        var zoom_level = 14;
        var map = L.map('map').setView(map_center, zoom_level);
        L.tileLayer('https://{server}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            server: 'a',  // can be 'a', 'b', or 'c'
            // must leave attribution in!
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        }).addTo(map);

        <!-- L.Icon.Default.prototype.options.iconSize = 15; -->
        <!-- L.Icon.Default.prototype.options.iconAnchor = [0, 0]; -->
        <!-- L.Icon.Default.prototype.options.shadowSize = 15; -->
        <!-- L.Icon.Default.prototype.options.shadowAnchor = [0, 0]; -->

        {% for sighting in sightings %}
          var point_lat_lon = [{{ sighting.Y }}, {{ sighting.X }}];
          var marker = L.marker(point_lat_lon).addTo(map);
        {% endfor %}
    </script>
  </body>
</html>

tracker/templates/tracker/sightings.html
{% extends 'tracker/base.html' %}

{% load static %}

{% block title %} - All Sightings{% endblock %}

{% block main %}
<!doctype html>
<html>
        <body>
	<p></p>	
	<b style="font-size:25px">All Squirrel Sightings</b>
	<p></p>
	<form>
	<button class="btn btn-outline-secondary" formaction="{% url 'tracker:add' %}">Add More Sightings</button>
	</form>
	<p></p>
	<p></p>
	<div class = "table-reponsive">
	  <table class="table table-striped table-sm">
	    <thead>
	      <tr>
		<th>Unique Squirrel ID</th>
		<th>Date</th>
	      </tr>
	    <tbody>
		{% for squirrel in squirrels %}
		  <tr>
	  	    <td>	  
			<a href="{% url 'tracker:detail' squirrel.Unique_Squirrel_ID %}">{{ squirrel.Unique_Squirrel_ID }} </a></td>
		    <td>{{squirrel.Date}}</td>
		  </tr>
		{% endfor %}	
	    </tbody>
	  </div>
	</table>
	</body>
</html>
{% endblock %}

tracker/templates/tracker/stat.html
{% extends 'tracker/base.html' %}
{% load static %}
{% block title %} -Squirrel Stats {% endblock %} 
{% block main  %}


<!doctype html>
<html>
	<body>
	  <div class="col-md-30">
                <div class="card mb-8 shadow-sm">
                  <div class="card-body">
                    <p class="card-text">
                      <b>Squirrels Status Information</b>
        	      <ul>
                	{% for stat in stats %}
			<li>{{stat}}</li>
                	{% endfor %}
		      </ul>
		    </p>
		  </div>
		</div>
	  </div>
        </body>
</html>
{% endblock %}